# Generated by Django 5.2.9 on 2025-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_material',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
